FROM ruby:3.2-slim-bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV TZ=Europe/Vienna

RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://deb.nodesource.com/setup_18.x | bash - \
    && curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update && apt-get install -y nodejs && npm install -g pnpm && npm install -g yarn

RUN apt-get install -y build-essential software-properties-common locales wget links curl gnupg2 rsync bc git git-core apt-transport-https libxml2 libxml2-dev libcurl4-openssl-dev gawk libreadline6-dev libyaml-dev autoconf libgdbm-dev libncurses5-dev automake libtool bison libffi-dev zlib1g-dev openssl tzdata xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libgeos-dev libproj-dev ghostscript ffmpeg libtag1-dev libavformat-dev libmpg123-dev libsamplerate-dev libsndfile-dev cimg-dev libavcodec-dev libswscale-dev openssh-client ca-certificates less mupdf mupdf-tools vim libvips42 webp \
  && update-ca-certificates

# PostgreSQL
RUN add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main"
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get install -y libpq-dev postgresql-16 postgresql-client-16

# pHash
RUN git clone https://github.com/aetilius/pHash.git /tmp/phash
RUN cd /tmp/phash \
    && git -c advice.detachedHead=false checkout 4bd5fc669f7d50ba2ae7a3f5524df56b3e4f96ca \
    && autoreconf -vif \
    && ./configure --disable-video-hash --disable-audio-hash --disable-pthread \
    && make \
    && make install

WORKDIR /var/app

RUN useradd --create-home ruby \
  && chown -R ruby:ruby /var/app

ENV PATH="${PATH}:/home/ruby/.local/bin" \
    USER="ruby"

USER ruby

RUN mkdir -p /var/app/vendor/gems/data-cycle-core/
RUN mkdir -p /var/app/vendor/gems/datacycle-schema-common/

RUN gem install bundler

COPY --chown=ruby:ruby Gemfile* /var/app/
COPY vendor/gems/data-cycle-core/GemfileCore /var/app/vendor/gems/data-cycle-core/
COPY vendor/gems/data-cycle-core/data_cycle_core.gemspec /var/app/vendor/gems/data-cycle-core
COPY vendor/gems/data-cycle-core/GEM_VERSION /var/app/vendor/gems/data-cycle-core
COPY vendor/gems/datacycle-schema-common/datacycle-schema-common.gemspec /var/app/vendor/gems/datacycle-schema-common
COPY vendor/gems/datacycle-schema-common/GEM_VERSION /var/app/vendor/gems/datacycle-schema-common/

RUN bundle install

COPY --chown=ruby:ruby  package.json /var/app
# COPY --chown=ruby:ruby pnpm-lock.yaml /var/app
COPY --chown=ruby:ruby vendor/gems/data-cycle-core/package.json /var/app/vendor/gems/data-cycle-core

RUN pnpm i

COPY --chown=ruby:ruby . .

ENTRYPOINT ["/var/app/docker/web/bin/entrypoint.sh"]

CMD ["bash"]
